version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wwwroot:/www/wwwroot:wr
      # nginx 基本配置文件
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/config.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./configs/nginx/vhost/:/etc/nginx/vhost:ro
    privileged: true
    networks:
      - default
    container_name: nginx